// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `contact_id_from_hex`, `load_graph`, `save_graph`, `summarize_contacts`, `tier_label`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// List contacts from a previously-sealed trust graph. `sealed` is `None` for a device with
/// no contacts yet (no invites completed).
List<ContactSummary> listContacts({
  Uint8List? sealed,
  required String passphrase,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiContactsListContacts(
  sealed: sealed,
  passphrase: passphrase,
  now: now,
);

/// What a contacts screen needs to show for one contact.
class ContactSummary {
  /// The contact's local, non-networkable handle, as lowercase hex — compare this against
  /// what the contact sees on their own "signed in" screen to confirm you added the right
  /// person.
  final String fingerprintHex;
  final String tier;

  const ContactSummary({required this.fingerprintHex, required this.tier});

  @override
  int get hashCode => fingerprintHex.hashCode ^ tier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactSummary &&
          runtimeType == other.runtimeType &&
          fingerprintHex == other.fingerprintHex &&
          tier == other.tier;
}
