// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_encode`, `summarize`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Generate a brand-new identity from OS randomness.
IdentitySummary createIdentity({required String nickname}) =>
    RustLib.instance.api.crateApiIdentityCreateIdentity(nickname: nickname);

/// Deterministically restore an identity from a 24-word recovery phrase the user typed in.
/// The same phrase always yields the same `local_id_hex` — that's how the user confirms
/// they entered it correctly.
IdentitySummary restoreIdentity({
  required String recoveryPhrase,
  required String nickname,
}) => RustLib.instance.api.crateApiIdentityRestoreIdentity(
  recoveryPhrase: recoveryPhrase,
  nickname: nickname,
);

/// What a "create" or "restore" screen needs to show the user immediately afterward.
class IdentitySummary {
  /// The local, non-networkable handle for this identity, as lowercase hex — a short,
  /// stable fingerprint the user can compare across devices.
  final String localIdHex;
  final String nickname;

  /// The 24-word BIP39 recovery phrase. Highly sensitive: the UI must treat this like the
  /// secret it is (no analytics, no accidental logging, cleared from the screen once the
  /// user confirms they've written it down).
  final List<String> recoveryWords;

  const IdentitySummary({
    required this.localIdHex,
    required this.nickname,
    required this.recoveryWords,
  });

  @override
  int get hashCode =>
      localIdHex.hashCode ^ nickname.hashCode ^ recoveryWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentitySummary &&
          runtimeType == other.runtimeType &&
          localIdHex == other.localIdHex &&
          nickname == other.nickname &&
          recoveryWords == other.recoveryWords;
}
