// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contacts.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InviteBookHandle>>
abstract class InviteBookHandle implements RustOpaqueInterface {
  /// Complete a pending invite: validate `token_text` against this issuer's own
  /// bookkeeping (rejecting it if already used, expired, or unknown — same as
  /// [`InviteBook::redeem`](lattice_core::invite::InviteBook::redeem)), then add the
  /// invitee as a Tier-0 contact under `contact_fingerprint_hex` in the trust graph
  /// (`existing_sealed_graph`, or a fresh one if this is the first contact).
  CompletedInvite complete({
    required String tokenText,
    required String contactFingerprintHex,
    Uint8List? existingSealedGraph,
    required String passphrase,
    required PlatformInt64 now,
  });

  /// Issue a fresh invite valid for `ttl_secs` from `now`, returned as hex text to share.
  String issue({required PlatformInt64 ttlSecs, required PlatformInt64 now});

  factory InviteBookHandle() =>
      RustLib.instance.api.crateApiInviteInviteBookHandleNew();
}

/// The result of successfully completing an invite: the newly-sealed trust graph to persist,
/// and the up-to-date contact list to display.
class CompletedInvite {
  final Uint8List sealedGraph;
  final List<ContactSummary> contacts;

  const CompletedInvite({required this.sealedGraph, required this.contacts});

  @override
  int get hashCode => sealedGraph.hashCode ^ contacts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletedInvite &&
          runtimeType == other.runtimeType &&
          sealedGraph == other.sealedGraph &&
          contacts == other.contacts;
}
